<?xml version="1.0"?>
<robot name="ship" xmlns:xacro="http://ros.org/wiki/xacro">

<!--Base dimensions-->
<xacro:property name="base_link_x" value="1" />
<xacro:property name="base_link_y" value="0.6" />
<xacro:property name="base_link_z" value="0.3" />

<!--Wheel dimensions-->
<xacro:property name="wheel_link_radius" value="0.15" />
<xacro:property name="wheel_link_length" value="0.1" />
<xacro:property name="wheel_link_z" value="-0.1" />

<!--Caster dimensions-->
<xacro:property name="caster_link_radius" value="0.15" />
<xacro:property name="caster_link_z" value="-0.1" />

<!--Material density-->
<xacro:property name="base_density" value="2710.0" />
<xacro:property name="wheel_density" value="2710.0" />
<xacro:property name="caster_density" value="2710.0" />

<!--Pi constant-->
<xacro:property name="pi_const" value="3.14159265" />

<!--Robot mass-->
<xacro:property name="base_mass" value="${base_density*base_link_x*base_link_y*base_link_z}" />
<xacro:property name="wheel_mass" value="${wheel_density*pi_const*wheel_link_radius*wheel_link_radius*wheel_link_length}" />
<xacro:property name="caster_mass" value="${caster_density*(4.0/3.0)*pi_const*caster_link_radius*caster_link_radius*caster_link_radius}" />

<!--Moments of inetria of the wheel-->
<xacro:property name="Iz_wheel" value="${0.5*wheel_mass*wheel_link_radius*wheel_link_radius}" />
<xacro:property name="I_wheel" value="${(1.0/12.0)*wheel_mass*(3.0*wheel_link_radius*wheel_link_radius+wheel_link_length*wheel_link_length)}" />

<!--Moments of inetria of the caster-->
<xacro:property name="I_caster" value="${(2.0/5.0)*caster_mass*caster_link_radius*caster_link_radius}" />

<!--Macro of the complete inertial section wheel-->
<xacro:macro name="inertia_wheel">
    <inertial>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <mass value="${wheel_mass}"/>
    <inertia ixx="${I_wheel}" ixy="0.0" ixz="0.0" iyy="${I_wheel}" iyz="0.0" izz="${Iz_wheel}"/>
    </inertial>
</xacro:macro>

<!--Macro of the complete inertial section caster-->
<xacro:macro name="inertia_caster">
    <inertial>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <mass value="${caster_mass}"/>
    <inertia ixx="${I_caster}" ixy="0.0" ixz="0.0" iyy="${I_caster}" iyz="0.0" izz="${I_caster}"/>
    </inertial>
</xacro:macro>

<!--Gazeboda robotumuzun görüntülenmesi için gazebo parametrelerini belirtmemiz gerekiyor-->
<xacro:include filename="$(find ship_description)/models/robot.gazebo" />

    <material name="grey">
	        <color rgba="0.5 0.5 0.5 1" />
    	</material>
	
	<material name="blue">
   		<color rgba="0 0 0.8 1"/>
  	</material>

    
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_link_x} ${base_link_y} ${base_link_z}" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </visual>

        <collision>
            <geometry>
                <box size="${base_link_x} ${base_link_y} ${base_link_z}" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </collision>

        <inertial>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <mass value="${base_mass}"/>
            <inertia ixx="${(1.0/12.0)*base_mass*(base_link_y*base_link_y+base_link_z*base_link_z)}" ixy="0" ixz="0" iyy="${(1/12)*base_mass*(base_link_y*base_link_y+base_link_z*base_link_z)}" iyz="0" izz="${(1/12)*base_mass*(base_link_y*base_link_y+base_link_z*base_link_z)}"/>
        </inertial>
    </link>
 
   
    <joint name="imu_joint" type="fixed">
       <parent link="base_link" />
       <child link="imu_link" />
       <origin xyz="0 0 ${base_link_y/2}" />
   </joint>
   
   <link name="imu_link">
        <visual>
            <geometry>
                <box size="0.1 0.1 0.1" />
            </geometry>
        </visual>

        <collision>
            <geometry>
                <box size="0.1 0.1 0.1" />
            </geometry>
        </collision>

        <inertial>
            <mass value=".1" />
            <inertia ixx="0.145833" ixy="0.0" ixz="0.0" iyy="0.145833" iyz="0.0" izz="0.125" />
        </inertial>
    </link>

    <joint name="laser_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_scan"/>
        <origin xyz="0.3 0 0.2" rpy="0 0 0"/>
    </joint>

    <link name="base_scan">
        <visual>
            <geometry>
                <cylinder radius="0.03" length="0.05"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.03" length="0.05"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.1"/>
            <inertia ixx="0.0001" iyy="0.0001" izz="0.0001"/>
        </inertial>
    </link>
    
    <joint name="wheel1_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel1_link"/>
        <origin xyz="${-2*wheel_link_radius} ${-base_link_y/2-wheel_link_length/2} ${wheel_link_z}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit effort="1000" velocity="1000"/>
        <dynamics damping="1.0" friction="1.0"/>
    </joint>

    <link name="wheel1_link">
        <visual>
            <origin rpy="1.570795 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
            </geometry>
        </visual>

        <collision>
            <origin rpy="1.570795 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
            </geometry>
        </collision>

        <xacro:inertia_wheel />
    </link>

    <joint name="wheel2_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel2_link"/>
        <origin xyz="${-2*wheel_link_radius} ${base_link_y/2+wheel_link_length/2} ${wheel_link_z}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit effort="1000" velocity="1000"/>
        <dynamics damping="1.0" friction="1.0"/>
    </joint>

    <link name="wheel2_link">
        <visual>
            <origin rpy="1.570795 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
            </geometry>
        </visual>

        <collision>
            <origin rpy="1.570795 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
            </geometry>
        </collision>

        <xacro:inertia_wheel />
    </link>

    <joint name="caster_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster_link"/>
        <origin xyz="${2*caster_link_radius} 0 ${caster_link_z}" rpy="0 0 0"/>
    </joint>

    <link name="caster_link">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <sphere radius="${caster_link_radius}"/>
            </geometry>
        </visual>

        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <sphere radius="${caster_link_radius}"/>
            </geometry>
        </collision>

        <xacro:inertia_caster />
    </link>

    
</robot>

